### ISSUE TITLE
Add wool touch sound

### ISSUE THREAD

**Issue by Picajoluna** [WalrusNetwork/bugs#16]
Add a reward sound upon player picking up the wool.

**Comment by mattarnold98** [comment]
Is this only for the first touch of the wool or for any touch at all?

**Comment by Picajoluna** [comment]
@mattarnold98 I think for the first time that a given player picks up a wool that their team hasn't capped yet. If the player dies, and the player manages to get back into the wool room, I don't think they'd hear the sound again as they've already touched the wool.

Alternatively, if the above isn't super feasible, it could be for the first time that any player of the team touches an un-capped wool. If the player dies, and another player makes it into the wool-room, since that wool is already touched, there would be no sound.

I'd prefer the first option over the second nonetheless.

**Comment by mattarnold98** [comment]
Changed the plugin so the sound should now be present regardless of the source of the touch (previously only happened when picking an item up off the floor, not transferring from chest).

UI problem now

in ctw ui file:
```properties
games.ocn.ctw.pickup.self=
games.ocn.ctw.pickup.team=
games.ocn.ctw.pickup.enemy=none
games.ocn.ctw.pickup.spectator=
```

**Comment by Picajoluna** [comment]
I set these to WITHER_SPAWN which I thought was kinda cool.

```properties
games.ocn.ctw.pickup.self=WITHER_SPAWN:1:0.3
games.ocn.ctw.pickup.team=none
games.ocn.ctw.pickup.enemy=none
games.ocn.ctw.pickup.spectator=none
```
